---

- name: VOTING APP | Install prerequisites
  hosts: masters
  remote_user: vagrant
  become: yes
  tasks:
    - name: VOTING APP | Install dependencies
      package:
        name: python-pip
        state: present
      tags: always
    - name: VOTING APP | Install Openshift client
      pip:
        name: openshift
        state: present
      tags: always

- hosts: masters
  remote_user: vagrant
  roles:
    - voting
