---

- name: VOTING APP 08 | Manage Vote Deployment
  k8s:
    state: present
    force: yes
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ item.name }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        template:
          metadata:
            labels:
              app: "{{ item.name }}"
          spec:
            affinity:
              podAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - redis
                  topologyKey: "kubernetes.io/hostname"
            containers:
            - name: "{{ item.name }}"
              image: "{{ item.image }}"
              env:
                - name: "REDIS_SERVICE_NAME"
                  valueFrom:
                    configMapKeyRef:
                      name: redis
                      key: service.name
                - name: "PORT"
                  valueFrom:
                    configMapKeyRef:
                      name: vote
                      key: port
                - name: "OPTION_A"
                  valueFrom:
                    configMapKeyRef:
                      name: vote
                      key: option_a
                - name: "OPTION_B"
                  valueFrom:
                    configMapKeyRef:
                      name: vote
                      key: option_b
              livenessProbe:
                httpGet:
                  path: /
                  port: vote
                initialDelaySeconds: 3
                periodSeconds: 3
              ports:
                - name: vote
                  containerPort: 8080
  with_items: "{{ vote_deployment }}"
