---

- name: VOTING APP 11 | Manage Database NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: db
        namespace: "{{ app_namespace }}"
      spec:
        podSelector:
          matchLabels:
            app: db
        policyTypes:
        - Ingress
        ingress:
        - from:
          - podSelector:
              matchLabels:
                app: result
          - podSelector:
              matchLabels:
                app: worker
          ports:
          - protocol: TCP
            port: 5432
