---

- name: VOTING APP 11 | Manage Namespace Default Ingress NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: default-deny-ingress
        namespace: "{{ app_namespace }}"
      spec:
        podSelector: {}
        policyTypes:
        - Ingress

- name: VOTING APP 11 | Manage Namespace Default Egress NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: default-allow-egress
        namespace: "{{ app_namespace }}"
      spec:
        podSelector: {}
        policyTypes:
        - Egress
        egress:
        - {}
