---

- name: VOTING APP 11 | Manage Vote NetworkPolicy
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: vote
        namespace: "{{ app_namespace }}"
      spec:
        podSelector:
          matchLabels:
            app: vote
        policyTypes:
        - Ingress
        ingress:
        - from:
          - ipBlock:
              cidr: 172.17.0.0/16
          ports:
          - protocol: TCP
            port: 5000
