---

- name: VOTING APP 01 | Manage Database Deployment
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ item.name }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        template:
          metadata:
            labels:
              app: "{{ item.name }}"
          spec:
            containers:
            - name: "{{ item.name }}"
              image: "{{ item.image }}"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: db-data
            volumes:
              - name: db-data
                emptyDir: {}
  with_items: "{{ database_deployment }}"
