---

- name: VOTING APP 01 | Manage Services
  import_tasks: services.yml

- name: VOTING APP 01 | Manage Database
  import_tasks: database.yml

- name: VOTING APP 01 | Manage Redis Queue
  import_tasks: redis.yml

- name: VOTING APP 01 | Manage Result App
  import_tasks: result.yml

- name: VOTING APP 01 | Manage Vote App
  import_tasks: vote.yml

- name: VOTING APP 01 | Manage Worker App
  import_tasks: worker.yml
