---

- name: VOTING APP 09 | Manage Vote AutoScaling
  k8s:
    state: present
    definition:
      apiVersion: autoscaling/v2beta1
      kind: HorizontalPodAutoscaler
      metadata:
        name: vote
        namespace: "{{ app_namespace }}"
      spec:
        scaleTargetRef:
          apiVersion: apps/v1
          kind: Deployment
          name: vote
        minReplicas: 1
        maxReplicas: 5
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 50
