---

- name: VOTING APP 06 | Manage Database StatefulSet
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ item.name }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        template:
          metadata:
            labels:
              app: "{{ item.name }}"
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - k8s-worker01
            containers:
            - name: "{{ item.name }}"
              image: "{{ item.image }}"
              env:
                - name: "DB_NAME"
                  valueFrom:
                    configMapKeyRef:
                      name: db
                      key: db.name
                - name: "DB_USERNAME"
                  valueFrom:
                    secretKeyRef:
                      name: db
                      key: username
                - name: "DB_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: db
                      key: password
              volumeMounts:
                - mountPath: /var/lib/postgresql/data
                  name: db-data
            volumes:
            - name: db-data
              hostPath:
                path: "{{ item.volume_hostPath }}"
                type: Directory
  with_items: "{{ database_statefulset }}"
