---

- name: VOTING APP 04 | Manage Result Deployment
  k8s:
    state: present
    force: yes
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ item.name }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        template:
          metadata:
            labels:
              app: "{{ item.name }}"
          spec:
            affinity:
              podAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - db
                  topologyKey: "kubernetes.io/hostname"
            containers:
            - name: "{{ item.name }}"
              image: "{{ item.image }}"
              env:
                - name: "DB_SERVICE_NAME"
                  valueFrom:
                    configMapKeyRef:
                      name: db
                      key: service.name
                - name: "DB_NAME"
                  valueFrom:
                    configMapKeyRef:
                      name: db
                      key: db.name
                - name: "DB_USERNAME"
                  valueFrom:
                    secretKeyRef:
                      name: db
                      key: username
                - name: "DB_PASSWORD"
                  valueFrom:
                    secretKeyRef:
                      name: db
                      key: password
                - name: "PORT"
                  value: "8080"
  with_items: "{{ result_deployment }}"
